## find all
GET http://localhost:8080/document
Accept: application/json

###

## Find by ID
GET http://localhost:8080/document/1
Accept: application/json

###

//beszúrás
POST http://localhost:8080/document
Content-Type: application/json

{
  "documentName": "Szuper doksi",
  "mimeType": "docx",
  "documentUrl": "/randomMappa/random/"
}
###

//módosítás
PUT http://localhost:8080/document
Content-Type: application/json

{
  "id": 1,
  "folderName": "TEST",
  "folderUrl": "Szuper URL"
}
###

## Delete by ID
DELETE http://localhost:8080/document/1
Accept: application/json
