## find all
GET http://localhost:8080/folder
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJGb2xkZXJEb2NzIiwiZXhwIjo5MjIzMzcyMDM2ODU0Nzc1LCJ1c2VybmFtZSI6InZhbGFraSJ9.UXvpSOAGd-y_gGrpAUR2sHkFgkvPv6u4aGZFULkSM6A

###

## Find by ID
GET http://localhost:8080/folder/57
Accept: application/json

###

//beszúrás
POST http://localhost:8080/folder
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJGb2xkZXJEb2NzIiwiZXhwIjo5MjIzMzcyMDM2ODU0Nzc1LCJ1c2VybmFtZSI6InZhbGFraSJ9.UXvpSOAGd-y_gGrpAUR2sHkFgkvPv6u4aGZFULkSM6A

{
  "folderName": "random",
  "folderUrl": "/",
  "description": "asd",
  "color": "red"
}
###

//módosítás
PUT http://localhost:8080/folder
Content-Type: application/json

{
  "id": 1,
  "folderName": "TEST",
  "folderUrl": "Szuper URL"
}
###

## Delete by ID
DELETE http://localhost:8080/folder/12
Accept: application/json
